"use client";
import dynamic from "next/dynamic";

const widgets: Record<string, ReturnType<typeof dynamic>> = {
  // Text
  "word-counter": dynamic(() => import("./word-counter").then((m) => m.default), { ssr: false }),
  "character-counter": dynamic(() => import("./character-counter").then((m) => m.default), { ssr: false }),
  "case-converter": dynamic(() => import("./case-converter").then((m) => m.default), { ssr: false }),
  "lorem-ipsum": dynamic(() => import("./lorem-ipsum").then((m) => m.default), { ssr: false }),
  "text-reverser": dynamic(() => import("./text-reverser").then((m) => m.default), { ssr: false }),
  "text-diff": dynamic(() => import("./text-diff").then((m) => m.default), { ssr: false }),
  // Developer
  "json-formatter": dynamic(() => import("./json-formatter").then((m) => m.default), { ssr: false }),
  "json-csv": dynamic(() => import("./json-csv").then((m) => m.default), { ssr: false }),
  "base64": dynamic(() => import("./base64").then((m) => m.default), { ssr: false }),
  "url-encoder": dynamic(() => import("./url-encoder").then((m) => m.default), { ssr: false }),
  "html-entities": dynamic(() => import("./html-entities").then((m) => m.default), { ssr: false }),
  "jwt-decoder": dynamic(() => import("./jwt-decoder").then((m) => m.default), { ssr: false }),
  "hash-generator": dynamic(() => import("./hash-generator").then((m) => m.default), { ssr: false }),
  "uuid-generator": dynamic(() => import("./uuid-generator").then((m) => m.default), { ssr: false }),
  "regex-tester": dynamic(() => import("./regex-tester").then((m) => m.default), { ssr: false }),
  "minifier": dynamic(() => import("./minifier").then((m) => m.default), { ssr: false }),
  // Image
  "image-converter": dynamic(() => import("./image-converter").then((m) => m.default), { ssr: false }),
  "image-compressor": dynamic(() => import("./image-compressor").then((m) => m.default), { ssr: false }),
  "image-resizer": dynamic(() => import("./image-resizer").then((m) => m.default), { ssr: false }),
  "image-to-base64": dynamic(() => import("./image-to-base64").then((m) => m.default), { ssr: false }),
  "favicon-generator": dynamic(() => import("./favicon-generator").then((m) => m.default), { ssr: false }),
  // Color
  "color-picker": dynamic(() => import("./color-picker").then((m) => m.default), { ssr: false }),
  "gradient-generator": dynamic(() => import("./gradient-generator").then((m) => m.default), { ssr: false }),
  "color-palette": dynamic(() => import("./color-palette").then((m) => m.default), { ssr: false }),
  "contrast-checker": dynamic(() => import("./contrast-checker").then((m) => m.default), { ssr: false }),
  // Generators
  "password-generator": dynamic(() => import("./password-generator").then((m) => m.default), { ssr: false }),
  "qr-generator": dynamic(() => import("./qr-generator").then((m) => m.default), { ssr: false }),
  "random-number": dynamic(() => import("./random-number").then((m) => m.default), { ssr: false }),
  "slug-generator": dynamic(() => import("./slug-generator").then((m) => m.default), { ssr: false }),
  // Calculators
  "unit-converter": dynamic(() => import("./unit-converter").then((m) => m.default), { ssr: false }),
  "percentage-calculator": dynamic(() => import("./percentage-calculator").then((m) => m.default), { ssr: false }),
  "age-calculator": dynamic(() => import("./age-calculator").then((m) => m.default), { ssr: false }),
  "bmi-calculator": dynamic(() => import("./bmi-calculator").then((m) => m.default), { ssr: false }),
  "tip-calculator": dynamic(() => import("./tip-calculator").then((m) => m.default), { ssr: false }),
  // Datetime
  "timestamp-converter": dynamic(() => import("./timestamp-converter").then((m) => m.default), { ssr: false }),
  "timezone-converter": dynamic(() => import("./timezone-converter").then((m) => m.default), { ssr: false }),
  "date-diff": dynamic(() => import("./date-diff").then((m) => m.default), { ssr: false }),
  // SEO
  "meta-tag-generator": dynamic(() => import("./meta-tag-generator").then((m) => m.default), { ssr: false }),
  "og-preview": dynamic(() => import("./og-preview").then((m) => m.default), { ssr: false }),
  "robots-generator": dynamic(() => import("./robots-generator").then((m) => m.default), { ssr: false }),
  // AI
  "ai-summarizer": dynamic(() => import("./ai-summarizer").then((m) => m.default), { ssr: false }),
  "ai-paraphraser": dynamic(() => import("./ai-paraphraser").then((m) => m.default), { ssr: false }),
  "ai-translator": dynamic(() => import("./ai-translator").then((m) => m.default), { ssr: false }),
  // New: Text
  "text-cleaner": dynamic(() => import("./text-cleaner").then((m) => m.default), { ssr: false }),
  "text-sorter": dynamic(() => import("./text-sorter").then((m) => m.default), { ssr: false }),
  "text-deduplicator": dynamic(() => import("./text-deduplicator").then((m) => m.default), { ssr: false }),
  "find-replace": dynamic(() => import("./find-replace").then((m) => m.default), { ssr: false }),
  "text-statistics": dynamic(() => import("./text-statistics").then((m) => m.default), { ssr: false }),
  "markdown-preview": dynamic(() => import("./markdown-preview").then((m) => m.default), { ssr: false }),
  "markdown-to-html": dynamic(() => import("./markdown-to-html").then((m) => m.default), { ssr: false }),
  "html-to-markdown": dynamic(() => import("./html-to-markdown").then((m) => m.default), { ssr: false }),
  "nato-phonetic": dynamic(() => import("./nato-phonetic").then((m) => m.default), { ssr: false }),
  "morse-code": dynamic(() => import("./morse-code").then((m) => m.default), { ssr: false }),
  "binary-text": dynamic(() => import("./binary-text").then((m) => m.default), { ssr: false }),
  "rot13": dynamic(() => import("./rot13").then((m) => m.default), { ssr: false }),
  "caesar-cipher": dynamic(() => import("./caesar-cipher").then((m) => m.default), { ssr: false }),
  "vigenere-cipher": dynamic(() => import("./vigenere-cipher").then((m) => m.default), { ssr: false }),
  "ascii-art-generator": dynamic(() => import("./ascii-art-generator").then((m) => m.default), { ssr: false }),
  "fancy-text": dynamic(() => import("./fancy-text").then((m) => m.default), { ssr: false }),
  "zalgo-text": dynamic(() => import("./zalgo-text").then((m) => m.default), { ssr: false }),
  "word-frequency": dynamic(() => import("./word-frequency").then((m) => m.default), { ssr: false }),
  "text-truncator": dynamic(() => import("./text-truncator").then((m) => m.default), { ssr: false }),
  "emoji-translator": dynamic(() => import("./emoji-translator").then((m) => m.default), { ssr: false }),
  "acronym-generator": dynamic(() => import("./acronym-generator").then((m) => m.default), { ssr: false }),
  "pig-latin": dynamic(() => import("./pig-latin").then((m) => m.default), { ssr: false }),
  "whitespace-remover": dynamic(() => import("./whitespace-remover").then((m) => m.default), { ssr: false }),
  "text-encoder-suite": dynamic(() => import("./text-encoder-suite").then((m) => m.default), { ssr: false }),
  // New: Developer
  "yaml-formatter": dynamic(() => import("./yaml-formatter").then((m) => m.default), { ssr: false }),
  "yaml-json-converter": dynamic(() => import("./yaml-json-converter").then((m) => m.default), { ssr: false }),
  "xml-formatter": dynamic(() => import("./xml-formatter").then((m) => m.default), { ssr: false }),
  "xml-json-converter": dynamic(() => import("./xml-json-converter").then((m) => m.default), { ssr: false }),
  "sql-formatter": dynamic(() => import("./sql-formatter").then((m) => m.default), { ssr: false }),
  "html-formatter": dynamic(() => import("./html-formatter").then((m) => m.default), { ssr: false }),
  "css-formatter": dynamic(() => import("./css-formatter").then((m) => m.default), { ssr: false }),
  "js-formatter": dynamic(() => import("./js-formatter").then((m) => m.default), { ssr: false }),
  "csv-formatter": dynamic(() => import("./csv-formatter").then((m) => m.default), { ssr: false }),
  "tsv-csv-converter": dynamic(() => import("./tsv-csv-converter").then((m) => m.default), { ssr: false }),
  "markdown-table-generator": dynamic(() => import("./markdown-table-generator").then((m) => m.default), { ssr: false }),
  "cron-parser": dynamic(() => import("./cron-parser").then((m) => m.default), { ssr: false }),
  "crontab-builder": dynamic(() => import("./crontab-builder").then((m) => m.default), { ssr: false }),
  "number-base-converter": dynamic(() => import("./number-base-converter").then((m) => m.default), { ssr: false }),
  "text-binary-hex": dynamic(() => import("./text-binary-hex").then((m) => m.default), { ssr: false }),
  "ascii-table": dynamic(() => import("./ascii-table").then((m) => m.default), { ssr: false }),
  "unicode-lookup": dynamic(() => import("./unicode-lookup").then((m) => m.default), { ssr: false }),
  "mime-types": dynamic(() => import("./mime-types").then((m) => m.default), { ssr: false }),
  "http-status-codes": dynamic(() => import("./http-status-codes").then((m) => m.default), { ssr: false }),
  "user-agent-parser": dynamic(() => import("./user-agent-parser").then((m) => m.default), { ssr: false }),
  "url-parser": dynamic(() => import("./url-parser").then((m) => m.default), { ssr: false }),
  "query-string-builder": dynamic(() => import("./query-string-builder").then((m) => m.default), { ssr: false }),
  "ip-subnet-calculator": dynamic(() => import("./ip-subnet-calculator").then((m) => m.default), { ssr: false }),
  "ipv4-to-ipv6": dynamic(() => import("./ipv4-to-ipv6").then((m) => m.default), { ssr: false }),
  "mac-vendor-lookup": dynamic(() => import("./mac-vendor-lookup").then((m) => m.default), { ssr: false }),
  "mac-address-generator": dynamic(() => import("./mac-address-generator").then((m) => m.default), { ssr: false }),
  "bcrypt-tester": dynamic(() => import("./bcrypt-tester").then((m) => m.default), { ssr: false }),
  "htpasswd-generator": dynamic(() => import("./htpasswd-generator").then((m) => m.default), { ssr: false }),
  "jwt-builder": dynamic(() => import("./jwt-builder").then((m) => m.default), { ssr: false }),
  "rsa-keypair-generator": dynamic(() => import("./rsa-keypair-generator").then((m) => m.default), { ssr: false }),
  "mock-data-generator": dynamic(() => import("./mock-data-generator").then((m) => m.default), { ssr: false }),
  "placeholder-image-url": dynamic(() => import("./placeholder-image-url").then((m) => m.default), { ssr: false }),
  "regex-cheatsheet-tool": dynamic(() => import("./regex-cheatsheet-tool").then((m) => m.default), { ssr: false }),
  "string-escaper": dynamic(() => import("./string-escaper").then((m) => m.default), { ssr: false }),
  // New: Image
  "image-cropper": dynamic(() => import("./image-cropper").then((m) => m.default), { ssr: false }),
  "image-rotator": dynamic(() => import("./image-rotator").then((m) => m.default), { ssr: false }),
  "image-watermark": dynamic(() => import("./image-watermark").then((m) => m.default), { ssr: false }),
  "image-grayscale": dynamic(() => import("./image-grayscale").then((m) => m.default), { ssr: false }),
  "image-blur": dynamic(() => import("./image-blur").then((m) => m.default), { ssr: false }),
  "image-pixelate": dynamic(() => import("./image-pixelate").then((m) => m.default), { ssr: false }),
  "image-color-extractor": dynamic(() => import("./image-color-extractor").then((m) => m.default), { ssr: false }),
  "image-color-picker": dynamic(() => import("./image-color-picker").then((m) => m.default), { ssr: false }),
  "svg-optimizer": dynamic(() => import("./svg-optimizer").then((m) => m.default), { ssr: false }),
  "svg-to-png": dynamic(() => import("./svg-to-png").then((m) => m.default), { ssr: false }),
  "png-to-ico": dynamic(() => import("./png-to-ico").then((m) => m.default), { ssr: false }),
  "image-metadata-viewer": dynamic(() => import("./image-metadata-viewer").then((m) => m.default), { ssr: false }),
  "image-exif-stripper": dynamic(() => import("./image-exif-stripper").then((m) => m.default), { ssr: false }),
  "image-to-ascii-art": dynamic(() => import("./image-to-ascii-art").then((m) => m.default), { ssr: false }),
  "image-mirror": dynamic(() => import("./image-mirror").then((m) => m.default), { ssr: false }),
  "image-noise": dynamic(() => import("./image-noise").then((m) => m.default), { ssr: false }),
  "gif-frame-extractor": dynamic(() => import("./gif-frame-extractor").then((m) => m.default), { ssr: false }),
  "webcam-photo-booth": dynamic(() => import("./webcam-photo-booth").then((m) => m.default), { ssr: false }),
  // New: Color
  "color-converter": dynamic(() => import("./color-converter").then((m) => m.default), { ssr: false }),
  "color-blindness-simulator": dynamic(() => import("./color-blindness-simulator").then((m) => m.default), { ssr: false }),
  "color-mixer": dynamic(() => import("./color-mixer").then((m) => m.default), { ssr: false }),
  "color-shades-tints": dynamic(() => import("./color-shades-tints").then((m) => m.default), { ssr: false }),
  "color-name-finder": dynamic(() => import("./color-name-finder").then((m) => m.default), { ssr: false }),
  "tailwind-palette": dynamic(() => import("./tailwind-palette").then((m) => m.default), { ssr: false }),
  "material-palette": dynamic(() => import("./material-palette").then((m) => m.default), { ssr: false }),
  "box-shadow-generator": dynamic(() => import("./box-shadow-generator").then((m) => m.default), { ssr: false }),
  "text-shadow-generator": dynamic(() => import("./text-shadow-generator").then((m) => m.default), { ssr: false }),
  "border-radius-generator": dynamic(() => import("./border-radius-generator").then((m) => m.default), { ssr: false }),
  "clip-path-generator": dynamic(() => import("./clip-path-generator").then((m) => m.default), { ssr: false }),
  "css-filter-generator": dynamic(() => import("./css-filter-generator").then((m) => m.default), { ssr: false }),
  // New: Generators
  "lorem-image": dynamic(() => import("./lorem-image").then((m) => m.default), { ssr: false }),
  "avatar-generator": dynamic(() => import("./avatar-generator").then((m) => m.default), { ssr: false }),
  "gravatar-url": dynamic(() => import("./gravatar-url").then((m) => m.default), { ssr: false }),
  "barcode-generator": dynamic(() => import("./barcode-generator").then((m) => m.default), { ssr: false }),
  "qr-wifi": dynamic(() => import("./qr-wifi").then((m) => m.default), { ssr: false }),
  "qr-vcard": dynamic(() => import("./qr-vcard").then((m) => m.default), { ssr: false }),
  "nanoid-generator": dynamic(() => import("./nanoid-generator").then((m) => m.default), { ssr: false }),
  "ulid-generator": dynamic(() => import("./ulid-generator").then((m) => m.default), { ssr: false }),
  "cuid-generator": dynamic(() => import("./cuid-generator").then((m) => m.default), { ssr: false }),
  "pin-generator": dynamic(() => import("./pin-generator").then((m) => m.default), { ssr: false }),
  "wifi-password-generator": dynamic(() => import("./wifi-password-generator").then((m) => m.default), { ssr: false }),
  "passphrase-generator": dynamic(() => import("./passphrase-generator").then((m) => m.default), { ssr: false }),
  "fake-name-generator": dynamic(() => import("./fake-name-generator").then((m) => m.default), { ssr: false }),
  "fake-address-generator": dynamic(() => import("./fake-address-generator").then((m) => m.default), { ssr: false }),
  "fake-credit-card": dynamic(() => import("./fake-credit-card").then((m) => m.default), { ssr: false }),
  "fake-iban": dynamic(() => import("./fake-iban").then((m) => m.default), { ssr: false }),
  "mock-json-builder": dynamic(() => import("./mock-json-builder").then((m) => m.default), { ssr: false }),
  "username-generator": dynamic(() => import("./username-generator").then((m) => m.default), { ssr: false }),
  "business-name-generator": dynamic(() => import("./business-name-generator").then((m) => m.default), { ssr: false }),
  "domain-name-generator": dynamic(() => import("./domain-name-generator").then((m) => m.default), { ssr: false }),
  "dice-roller": dynamic(() => import("./dice-roller").then((m) => m.default), { ssr: false }),
  "coin-flip": dynamic(() => import("./coin-flip").then((m) => m.default), { ssr: false }),
  "decision-wheel": dynamic(() => import("./decision-wheel").then((m) => m.default), { ssr: false }),
  "random-letter": dynamic(() => import("./random-letter").then((m) => m.default), { ssr: false }),
  // New: Calculators
  "loan-calculator": dynamic(() => import("./loan-calculator").then((m) => m.default), { ssr: false }),
  "mortgage-calculator": dynamic(() => import("./mortgage-calculator").then((m) => m.default), { ssr: false }),
  "compound-interest-calculator": dynamic(() => import("./compound-interest-calculator").then((m) => m.default), { ssr: false }),
  "simple-interest-calculator": dynamic(() => import("./simple-interest-calculator").then((m) => m.default), { ssr: false }),
  "salary-calculator": dynamic(() => import("./salary-calculator").then((m) => m.default), { ssr: false }),
  "discount-calculator": dynamic(() => import("./discount-calculator").then((m) => m.default), { ssr: false }),
  "sales-tax-calculator": dynamic(() => import("./sales-tax-calculator").then((m) => m.default), { ssr: false }),
  "roi-calculator": dynamic(() => import("./roi-calculator").then((m) => m.default), { ssr: false }),
  "markup-margin-calculator": dynamic(() => import("./markup-margin-calculator").then((m) => m.default), { ssr: false }),
  "gpa-calculator": dynamic(() => import("./gpa-calculator").then((m) => m.default), { ssr: false }),
  "grade-calculator": dynamic(() => import("./grade-calculator").then((m) => m.default), { ssr: false }),
  "body-fat-calculator": dynamic(() => import("./body-fat-calculator").then((m) => m.default), { ssr: false }),
  "calorie-calculator": dynamic(() => import("./calorie-calculator").then((m) => m.default), { ssr: false }),
  "macro-calculator": dynamic(() => import("./macro-calculator").then((m) => m.default), { ssr: false }),
  "pace-calculator": dynamic(() => import("./pace-calculator").then((m) => m.default), { ssr: false }),
  "pregnancy-due-date": dynamic(() => import("./pregnancy-due-date").then((m) => m.default), { ssr: false }),
  "fuel-economy-calculator": dynamic(() => import("./fuel-economy-calculator").then((m) => m.default), { ssr: false }),
  "ratio-calculator": dynamic(() => import("./ratio-calculator").then((m) => m.default), { ssr: false }),
  "average-mean-median-mode": dynamic(() => import("./average-mean-median-mode").then((m) => m.default), { ssr: false }),
  "permutation-combination": dynamic(() => import("./permutation-combination").then((m) => m.default), { ssr: false }),
  "quadratic-solver": dynamic(() => import("./quadratic-solver").then((m) => m.default), { ssr: false }),
  "fraction-calculator": dynamic(() => import("./fraction-calculator").then((m) => m.default), { ssr: false }),
  "data-storage-converter": dynamic(() => import("./data-storage-converter").then((m) => m.default), { ssr: false }),
  "bandwidth-converter": dynamic(() => import("./bandwidth-converter").then((m) => m.default), { ssr: false }),
  "cooking-converter": dynamic(() => import("./cooking-converter").then((m) => m.default), { ssr: false }),
  "shoe-size-converter": dynamic(() => import("./shoe-size-converter").then((m) => m.default), { ssr: false }),
  "clothing-size-converter": dynamic(() => import("./clothing-size-converter").then((m) => m.default), { ssr: false }),
  "wind-chill-calculator": dynamic(() => import("./wind-chill-calculator").then((m) => m.default), { ssr: false }),
  "heat-index-calculator": dynamic(() => import("./heat-index-calculator").then((m) => m.default), { ssr: false }),
  "ohms-law-calculator": dynamic(() => import("./ohms-law-calculator").then((m) => m.default), { ssr: false }),
  // New: Datetime
  "countdown-timer": dynamic(() => import("./countdown-timer").then((m) => m.default), { ssr: false }),
  "world-clock": dynamic(() => import("./world-clock").then((m) => m.default), { ssr: false }),
  "workday-calculator": dynamic(() => import("./workday-calculator").then((m) => m.default), { ssr: false }),
  "week-number-calculator": dynamic(() => import("./week-number-calculator").then((m) => m.default), { ssr: false }),
  "weekday-finder": dynamic(() => import("./weekday-finder").then((m) => m.default), { ssr: false }),
  "leap-year-checker": dynamic(() => import("./leap-year-checker").then((m) => m.default), { ssr: false }),
  "cron-next-run": dynamic(() => import("./cron-next-run").then((m) => m.default), { ssr: false }),
  "meeting-planner": dynamic(() => import("./meeting-planner").then((m) => m.default), { ssr: false }),
  "date-formatter": dynamic(() => import("./date-formatter").then((m) => m.default), { ssr: false }),
  "roman-numeral-date": dynamic(() => import("./roman-numeral-date").then((m) => m.default), { ssr: false }),
  "add-subtract-days": dynamic(() => import("./add-subtract-days").then((m) => m.default), { ssr: false }),
  "quarter-calculator": dynamic(() => import("./quarter-calculator").then((m) => m.default), { ssr: false }),
  "iso-week-calculator": dynamic(() => import("./iso-week-calculator").then((m) => m.default), { ssr: false }),
  "duration-calculator": dynamic(() => import("./duration-calculator").then((m) => m.default), { ssr: false }),
  // New: SEO
  "keyword-density": dynamic(() => import("./keyword-density").then((m) => m.default), { ssr: false }),
  "xml-sitemap-generator": dynamic(() => import("./xml-sitemap-generator").then((m) => m.default), { ssr: false }),
  "sitemap-validator": dynamic(() => import("./sitemap-validator").then((m) => m.default), { ssr: false }),
  "schema-markup-generator": dynamic(() => import("./schema-markup-generator").then((m) => m.default), { ssr: false }),
  "canonical-tag-generator": dynamic(() => import("./canonical-tag-generator").then((m) => m.default), { ssr: false }),
  "hreflang-generator": dynamic(() => import("./hreflang-generator").then((m) => m.default), { ssr: false }),
  "utm-builder": dynamic(() => import("./utm-builder").then((m) => m.default), { ssr: false }),
  "serp-snippet-preview": dynamic(() => import("./serp-snippet-preview").then((m) => m.default), { ssr: false }),
  "twitter-card-generator": dynamic(() => import("./twitter-card-generator").then((m) => m.default), { ssr: false }),
  "open-graph-image-generator": dynamic(() => import("./open-graph-image-generator").then((m) => m.default), { ssr: false }),
  "breadcrumb-jsonld": dynamic(() => import("./breadcrumb-jsonld").then((m) => m.default), { ssr: false }),
  "faq-jsonld": dynamic(() => import("./faq-jsonld").then((m) => m.default), { ssr: false }),
  "organization-jsonld": dynamic(() => import("./organization-jsonld").then((m) => m.default), { ssr: false }),
  "article-jsonld": dynamic(() => import("./article-jsonld").then((m) => m.default), { ssr: false }),
  // New: AI
  "ai-grammar-checker": dynamic(() => import("./ai-grammar-checker").then((m) => m.default), { ssr: false }),
  "ai-tone-changer": dynamic(() => import("./ai-tone-changer").then((m) => m.default), { ssr: false }),
  "ai-email-writer": dynamic(() => import("./ai-email-writer").then((m) => m.default), { ssr: false }),
  "ai-blog-title": dynamic(() => import("./ai-blog-title").then((m) => m.default), { ssr: false }),
  "ai-meta-description": dynamic(() => import("./ai-meta-description").then((m) => m.default), { ssr: false }),
  "ai-product-description": dynamic(() => import("./ai-product-description").then((m) => m.default), { ssr: false }),
  "ai-headline-generator": dynamic(() => import("./ai-headline-generator").then((m) => m.default), { ssr: false }),
  "ai-explainer": dynamic(() => import("./ai-explainer").then((m) => m.default), { ssr: false }),
  "ai-code-explainer": dynamic(() => import("./ai-code-explainer").then((m) => m.default), { ssr: false }),
  "ai-text-expander": dynamic(() => import("./ai-text-expander").then((m) => m.default), { ssr: false }),
};

export function ToolWidget({ slug }: { slug: string }) {
  const Widget = widgets[slug];
  if (!Widget) {
    return (
      <div className="rounded-xl border border-dashed border-[var(--color-border)] p-8 text-center text-sm text-[var(--color-muted)]">
        This tool isn&rsquo;t implemented yet.
      </div>
    );
  }
  return <Widget />;
}
