import type { Metadata } from "next";
import Link from "next/link";
import { SITE } from "@/lib/site";

const EFFECTIVE_DATE = "May 12, 2026";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of use for ${SITE.name}'s free online tools. Use the site at your own risk; AI output is not guaranteed accurate.`,
  alternates: { canonical: `${SITE.url}/terms` },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
      <nav className="text-sm text-[var(--color-muted)] mb-6">
        <Link href="/" className="hover:text-[var(--color-foreground)]">Home</Link>
        <span className="mx-2">/</span>
        <span>Terms</span>
      </nav>
      <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-[var(--color-muted)]">Last updated: {EFFECTIVE_DATE}</p>

      <div className="mt-10 space-y-8 text-[15px] leading-relaxed text-[var(--color-foreground)]/90">
        <section>
          <p>
            By using {SITE.name} (the &quot;Service&quot;), you agree to these Terms. If you do not agree, please do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">1. The Service</h2>
          <p>
            {SITE.name} provides a collection of free online utilities. Most tools run entirely inside your browser; a small number of tools labeled &quot;AI&quot; submit your input to a third-party AI provider (Google Gemini) to generate a response. See the <Link className="underline hover:text-[var(--color-accent)]" href="/privacy">Privacy Policy</Link> for details on data handling.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">2. Acceptable use</h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use the Service to generate content that is unlawful, harassing, defamatory, infringing, or otherwise harmful.</li>
            <li>Attempt to overload, scrape at scale, reverse engineer, or interfere with the Service or its infrastructure.</li>
            <li>Use the Service to attempt to bypass third-party rate limits, terms of service, or copyright.</li>
            <li>Submit personal information about other people to AI tools without a lawful basis.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">3. AI tools</h2>
          <p>
            Outputs from AI tools are generated by a machine-learning model and may be inaccurate, incomplete, or biased. You are responsible for reviewing and verifying any output before relying on it, particularly for legal, medical, financial, or safety-critical decisions. We make no warranty that AI output is correct or fit for any purpose.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">4. Intellectual property</h2>
          <p>
            The Service&apos;s design, code, copy, and branding are owned by {SITE.author} and protected by applicable IP laws. You may use the Service&apos;s public output (e.g., a formatted JSON string, a generated color palette) freely; you may not copy or redistribute the Service itself.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">5. No warranty</h2>
          <p>
            The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that the Service will be uninterrupted, secure, or error-free.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">6. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, {SITE.author} will not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, data, or use, arising out of or related to the Service. Our total aggregate liability for any claim arising out of or relating to the Service is limited to USD 50.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">7. Third-party services</h2>
          <p>
            The Service displays ads served by Google AdSense and routes AI tool requests through Google&apos;s Gemini API. Your use of those features is also subject to the relevant third-party terms, including <a className="underline hover:text-[var(--color-accent)]" href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer">Google&apos;s Terms of Service</a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">8. Changes</h2>
          <p>
            We may update these Terms from time to time. The &quot;Last updated&quot; date at the top reflects the most recent change. Continuing to use the Service after a change constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold tracking-tight mb-3">9. Contact</h2>
          <p>
            Questions about these Terms: <a className="underline hover:text-[var(--color-accent)]" href="mailto:contact@bestmint.com">contact@bestmint.com</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
